// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqdagFw0UrNAGomioQMgkjREIguSRQJ0A',
    appId: '1:737687305566:web:0d38a619c9b9b0122063cf',
    messagingSenderId: '737687305566',
    projectId: 'lab11-4b757',
    authDomain: 'lab11-4b757.firebaseapp.com',
    databaseURL: 'https://lab11-4b757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab11-4b757.firebasestorage.app',
    measurementId: 'G-8FV8SK8KDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB77_k7JJhvD6aCHsWD8FQ0slrarYcZ3Y',
    appId: '1:737687305566:android:f51dd16411bf6b3d2063cf',
    messagingSenderId: '737687305566',
    projectId: 'lab11-4b757',
    databaseURL: 'https://lab11-4b757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab11-4b757.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttFNAl4RJPSohBCVLb4sOuRUf2grZzi4',
    appId: '1:737687305566:ios:f2cb582f265fbe682063cf',
    messagingSenderId: '737687305566',
    projectId: 'lab11-4b757',
    databaseURL: 'https://lab11-4b757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab11-4b757.firebasestorage.app',
    iosBundleId: 'com.example.gymFitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCttFNAl4RJPSohBCVLb4sOuRUf2grZzi4',
    appId: '1:737687305566:ios:f2cb582f265fbe682063cf',
    messagingSenderId: '737687305566',
    projectId: 'lab11-4b757',
    databaseURL: 'https://lab11-4b757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab11-4b757.firebasestorage.app',
    iosBundleId: 'com.example.gymFitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqdagFw0UrNAGomioQMgkjREIguSRQJ0A',
    appId: '1:737687305566:web:f722de9b0c051af92063cf',
    messagingSenderId: '737687305566',
    projectId: 'lab11-4b757',
    authDomain: 'lab11-4b757.firebaseapp.com',
    databaseURL: 'https://lab11-4b757-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lab11-4b757.firebasestorage.app',
    measurementId: 'G-HLMYJYL8HR',
  );

}