import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// Import the AuthGate we created in Step 2.3
// Make sure this path matches your folder structure exactly
import 'features/auth/presentation/auth_gate.dart';

void main() async {
  // 1. Ensure Flutter bindings are ready before using platform channels
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase using the generated options for Android/iOS
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 3. Run the App wrapped in ProviderScope
  // ProviderScope is REQUIRED for Riverpod to work
  runApp(
    const ProviderScope(
      child: GymApp(),
    ),
  );
}

class GymApp extends StatelessWidget {
  const GymApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Gym & Fitness Tracker',
      debugShowCheckedModeBanner: false, // Removes the "Debug" banner

      // Define the App Theme (Visual Style)
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blueAccent,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        // You can customize fonts and text styles here later
      ),

      // THE KEY PART:
      // We don't set 'home' to LoginScreen or Dashboard directly.
      // We set it to AuthGate, which decides which one to show.
      home: const AuthGate(),
    );
  }
}